### PR TITLE
README - Proposal for translation-friendly writing -- updated installation-steps

### PR DESCRIPTION
**Pull request by claudiusraphael**
I have added a README---DEDE.md which is a ( where gramatically possible word by word translation ) to german, which might be an invitation for those that like to translate | localize.

I tried to convert the original README into a writing-structure that allows machine-translation to (hopefully) deliver understandable sentences. Translation by hand | mouth should be relatively easy that way, as the original content is split up in shortened parts, which can be translated on their own.

I tried to use a wording that is unique by sequence, but generic enough to have counterparts in the main spoken and written languages.

If you like what you see, i will go on to translate into german.

But then it would be necessary to know how the translated files should be named and organized so they are manageable by the originators.

If there is no interest in translated content i will translate for my own use ( and those who like to use it too) into a l10n|localization-DEDE-branch ); if there is a problem license-wise please inform me in forefront.

Thanks for your interest.

claudiusraphael

### CODE REVIEW

**Comment by AminaG** [comment]
I think it can be asesome. you should add the explanation and instructions to the readme files, not just here in the pull request. After than I can merge it.

**Comment by claudiusraphael** [comment]
@AminaG would you be so kind, to give an example for where (explicit location) and how (which formatting) you like to have the explanations|comments|translations.

Because, as soon as i start i will go on with as much as possible in one session.

Also it might be motivating for others | potential participants to know which guidelines are given for constructive work towards 'Open Screenshot'.

Btw.: Thanks for the fast response!

**Comment by AminaG** [comment]
The translation itself you put in [_locale](https://github.com/AminaG/OpenScreenshot/tree/master/chrome-extensions/_locales) folder, in the [message.json](https://github.com/AminaG/OpenScreenshot/blob/master/chrome-extensions/_locales/bg/messages.json) file

Read more:
https://developer.chrome.com/extensions/i18n

Here you see example how to  use it in the `package.json`:
https://github.com/AminaG/OpenScreenshot/blob/master/chrome-extensions/manifest.json#L2

We adding translation by using `tr` attibutes:

https://github.com/AminaG/OpenScreenshot/blob/master/chrome-extensions/popup.html#L31

This is the translation function:
https://github.com/AminaG/OpenScreenshot/blob/master/chrome-extensions/js/translate.js

It's search for elements contain `tr` attribute and search for the matching translation in the `manifest.json`

**Comment by claudiusraphael** [comment]
Thank you very much; I'll go into it.

**Comment by claudiusraphael** [comment]
TARGET: [Issue #36](https://github.com/AminaG/OpenScreenshot/issues/36)

ORIGIN: @AminaG --- #35 | Pull-Request-Comments

I did, so far, got it (i think):

- You follow the [guidelines, for extension-/app- -intern i18n | l10n](https://developer.chrome.com/extensions/i18n), and

- [You answered my question in very detail](https://github.com/AminaG/OpenScreenshot/pull/35#issuecomment-204268665), thank you for that, BUT :) :

My yet-unwritten attempt was: To ADD what is MISSING;

- Translations and informations about localized:

1. .usage ('How one WILL be doing stuff with Open Screenshot')(before it is installed)(for explanatorial use via the webpage|demo)
2. .content ('What one has to do to do ->INSERT-TARGET-OF-OPERATION<- successfully' - which is none but the yet-non-existing-wiki--localized---accessible from inside the extension, stored-as-github-wiki for fully accessible-internationalized-and-localized components and parts from where-ever-the-hell-could-freeze)
3. .documentation ('README' | 'source-code-comments' | 'full localized documentation of the source for educational purposes')
--
Let me give an example and explain why i thought, that the described before, would be great for your project;

--

- l10n=DEDE
:: for general use of [ DE==deutsch (german) - DE==Deutschland (Germany) ], CAPITALIZED because it would be a FLAG that sums-up|points-to the set of wished-l10n, combined with 404-like linking to an internal translation-proposal-page|sorry-notice as a-generic-one-in-ENUS plus one-that-is-if-possible-already-localized

--
- ... or for those that like to

1. translate
2. develop
3. use OpenScreenshot on non-localized (Host-)Systems

because for whatever reason|use-case, e.g.:
- deployment-given-in-enus
- no-rights-to-change-host-language
- no-possibility-to-change-host-language
- using diverse accounts, for the given different purposes  (whereas sync is active; so for a translator or learner the language-specific-presentation is comparable)

EXAM: The resulting call could be a set:

l10n={
 'messages':'dede'
,'hoverhelp':'dech'
,'helptext':'enus'
,'controls':'deat'
,'readme':'dede'
,'licensing':'enus'
};

I hope you get what i am aiming|asking for.

So, the question is just:

WHERE should the original readme (in enus) be mirrored|linked, so that a translation can be hold in the same storage for optional access (sorted for developers|translators into one folder-by-origfilename+locale; for direct editing | usable by the extension itself to blend the content in naturally, by allowing specific l10n-setting.

WHY?

Because ... you [already have a bunch of stuff translated](https://github.com/AminaG/OpenScreenshot/tree/develop/chrome-extensions/_locales) and i did not want to reinvent the wheel, but help make the extension complete, because:
- there is no open-source extension for chrom*, that has similar feature-sets, yet
- there is no open-source extension for chrom*, that has similar localization-support, yet
- there is no open-source extension for chrom*, that has similar well-structured code, yet
, which would be at all comparable to 'Open Screenshot'.

Also, i couldn't ignore the fact:
- you have [had no wiki setup yet](https://github.com/AminaG/OpenScreenshot/wiki) for the ['Open Screenshot'-Extension](https://github.com/AminaG/OpenScreenshot)
- your [latest commit to the developer branch is far back in time](https://github.com/AminaG/OpenScreenshot/commit/ae2903d4d915b6ddb8b825797dffaa2ae445b7b0) in comparison to [your commits to the master-branch](https://github.com/AminaG/OpenScreenshot/commit/b6449fd1a384fe32c829ebbbca3b3ce8e0895916)
- you make no use of [github-pages](https://pages.github.com/) -feature
which at all seems 'obviously missing', at least in respect of a fully setup github-collaborators open-source extension for chrome;

I think it would be very nice to spend the opportunity to deliver a FULL extension, just because [you already did it](https://chrome.google.com/webstore/detail/open-screenshot/akgpcdalpfphjmfifkmfbpdmgdmeeaeo), the only little things that are missing are the described parts ( which are for sure the main fractions in terms of file-size, but the ignorable in terms of coding complexity ).

I hope you do not feel upset, but instead encouraged by my explanation.

I just think Open Screenshot would be the PERFECT FUNDAMENTAL EXAMPLE OF A FULLY FUNCTIONAL SCREENSHOT EXTENSION FOR BROWSERS ( ... ;) yeahyeah i know its just for chrome, ahem ;) ... )

By the way, you obviously have defnitely absolutely NO PROBLEM to answer one that asks for details about your project; so you MIGHT BE ABLE to give the WHOLE EXPERIENCE a shot.

Okay, please tell me one last time what your thoughts are, i hope i gave enough details and examples what my thoughts have been. If not, or if you wish to dicuss this no further, just let me know, i won't take it in anyway as an offense, just speak open and freely.

NOTE: The CAPITALIZED WORDS are not a CRYOUT, but in sense of letter-by-letter-readable, so one can see the dimension and opportunities behind.

:)

Thanks for your interest. (btw.: Yes i COULD code that myself; No, i do not want to. And if you ask what my talents are, i name you one: having feelings when looking at structures leading to thoughts showing pathes of developments which themselve lead to final solutions ... Some call it Authism ;) )

As you may have noticed already, this is not just a further asking in the original pull request, but opened as a new issue, so others can add there own thoughts to it. As i already told, if there is no interest from your side its totally accepted, no offense taken, but at least: let it exist as an issue ( means: do not close, please ). One day, one might want to get into it, and even if not it contains some trackbacks and sidelinks, that will push your rankings in terms of better being found, for those that are in need of 'Open Screenshot'.n](https://developer.chrome.com/extensions/i18n), and
- [You answered my question in very detail](https://github.com/AminaG/OpenScreenshot/pull/35#issuecomment-204268665), thank you for that, BUT :) :

My attempt was: To ADD what is MISSING;

- Translations and informations about localized:

1. .usage ('How one WILL be doing stuff with Open Screenshot')(before it is installed)(for explanatorial use via the webpage|demo)
2. .content ('What one has to do to do ->INSERT-TARGET-OF-OPERATION<- successfully' - which is none but the yet-non-existing-wiki--localized---accessible from inside the extension, stored-as-github-wiki for fully accessible-internationalized-and-localized components and parts from where-ever-the-hell-could-freeze)
3. .documentation ('README' | 'source-code-comments' | 'full localized documentation of the source for educational purposes')
--
Let me give an example and explain why i thought, that the described before, would be great for your project;

--

- l10n=DEDE
:: for general use of [ DE==deutsch (german) - DE==Deutschland (Germany) ], CAPITALIZED because it would be a FLAG that sums-up|points-to the set of wished-l10n, combined with 404-like linking to an internal translation-proposal-page|sorry-notice as a-generic-one-in-ENUS plus one-that-is-if-possible-already-localized

--
- ... or for those that like to

1. translate
2. develop
3. use OpenScreenshot on non-localized (Host-)Systems

because for whatever reason|use-case, e.g.:
- deployment-given-in-enus
- no-rights-to-change-host-language
- no-possibility-to-change-host-language
- using diverse accounts, for the given different purposes  (whereas sync is active; so for a translator or learner the language-specific-presentation is comparable)

EXAM: The resulting call could be a set:

l10n={
 'messages':'dede'
,'hoverhelp':'dech'
,'helptext':'enus'
,'controls':'deat'
,'readme':'dede'
,'licensing':'enus'
};

I hope you get what i am aiming|asking for.

So, the question is just:

WHERE should the original readme (in enus) be mirrored|linked, so that a translation can be hold in the same storage for optional access (sorted for developers|translators into one folder-by-origfilename+locale; for direct editing | usable by the extension itself to blend the content in naturally, by allowing specific l10n-setting.

WHY?

Because ... you [already have a bunch of stuff translated](https://github.com/AminaG/OpenScreenshot/tree/develop/chrome-extensions/_locales) and i did not want to reinvent the wheel, but help make the extension complete, because:
- there is no open-source extension for chrom*, that has similar feature-sets, yet
- there is no open-source extension for chrom*, that has similar localization-support, yet
- there is no open-source extension for chrom*, that has similar well-structured code, yet
, which would be at all comparable to 'Open Screenshot'.

Also, i couldn't ignore the fact:
- you have [had no wiki setup yet](https://github.com/AminaG/OpenScreenshot/wiki) for the ['Open Screenshot'-Extension](https://github.com/AminaG/OpenScreenshot)
- your [latest commit to the developer branch is far back in time](https://github.com/AminaG/OpenScreenshot/commit/ae2903d4d915b6ddb8b825797dffaa2ae445b7b0) in comparison to [your commits to the master-branch](https://github.com/AminaG/OpenScreenshot/commit/b6449fd1a384fe32c829ebbbca3b3ce8e0895916)
- you make no use of [github-pages](https://pages.github.com/) -feature
which at all seems 'obviously missing', at least in respect of a fully setup github-collaborators open-source extension for chrome;

I think it would be very nice to spend the opportunity to deliver a FULL extension, just because [you already did it](https://chrome.google.com/webstore/detail/open-screenshot/akgpcdalpfphjmfifkmfbpdmgdmeeaeo), the only little things that are missing are the described parts ( which are for sure the main fractions in terms of file-size, but the ignorable in terms of coding complexity ).

I hope you do not feel upset, but instead encouraged by my explanation.

I just think Open Screenshot would be the PERFECT FUNDAMENTAL EXAMPLE OF A FULLY FUNCTIONAL SCREENSHOT EXTENSION FOR BROWSERS ( ... ;) yeahyeah i know its just for chrome, ahem ;) ... )

By the way, you obviously have defnitely absolutely NO PROBLEM to answer one that asks for details about your project; so you MIGHT BE ABLE to give the WHOLE EXPERIENCE a shot.

Okay, please tell me one last time what your thoughts are, i hope i gave enough details and examples what my thoughts have been. If not, or if you wish to dicuss this no further, just let me know, i won't take it in anyway as an offense, just speak open and freely.

NOTE: The CAPITALIZED WORDS are not a CRYOUT, but in sense of letter-by-letter-readable, so one can see the dimension and opportunities behind.

:)

Thanks for your interest. (btw.: Yes i COULD code that myself; No, i do not want to. And if you ask what my talents are, i name you one: having feelings when looking at structures leading to thoughts showing pathes of developments which themselve lead to final solutions ... Some call it Authism ;) )

As you may have noticed already, this is not just a further asking in the original pull request, but opened as a new issue, so others can add there own thoughts to it. As i already told, if there is no interest from your side its totally accepted, no offense taken, but at least: let it exist as an issue ( means: do not close, please ). One day, one might want to get into it, and even if not it contains some trackbacks and sidelinks, that will push your rankings in terms of better being found, for those that are in need of ['Open Screenshot'](https://www.google.de/search?client=ubuntu&channel=fs&q=versatile+screenshot+for+chrome&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=_sP-VsbpEaGh8wf50buoAg#channel=fs&q=screenshot+chrome+extension+open+source).

**Pull request closed without merging**
